<?php
/**
 * Part of framework-practice project. 
 *
 * @copyright  Copyright (C) 2011 - 2014 SMS Taiwan, Inc. All rights reserved.
 * @license    GNU General Public License version 2 or later; see LICENSE
 */

namespace Flower\Application;

use Joomla\Application\AbstractWebApplication;
use Joomla\Application\Web;
use Joomla\DI\Container;
use Joomla\Input\Input;
use Joomla\Registry\Registry;
use Provider\ActionProvider;
use Provider\WhoopsProvider;

class Application extends AbstractWebApplication
{
	/**
	 * Property container.
	 *
	 * @var  \Joomla\DI\Container
	 */
	public $container;

	public function __construct(Input $input = null, Registry $config = null, Web\WebClient $client = null)
	{
		$this->container = new Container;

		parent::__construct($input, $config, $client);
	}

	protected function initialise()
	{
		// TODO: Change the autogenerated stub
		$this->loadConfig();



		define('FLOWER_DEBUG', $this->get('system.debug'));

		if (FLOWER_DEBUG)
		{
			$this->container->registerServiceProvider(new WhoopsProvider);
		}

		$this->container->share('app', $this);
		$this->container->share('config', $this->config);

		$this->container->registerServiceProvider(new ActionProvider);
	}

	protected function loadConfig()
	{
		$file = FLOWER_ETC . '/config.json';

		if (!is_file($file))
		{
			echo "Please copy etc/config.dist.json to etc/config.json";

			die;
		}

		$this->config->loadFile($file);
	}

	/**
	 * Method to run the application routines.  Most likely you will want to instantiate a controller
	 * and execute it, or perform some sort of task directly.
	 *
	 * @return  void
	 *
	 * @since   1.0
	 */
	protected function doExecute()
	{
		/** @var $action \Flower\Sunflower\Action */
		$action = $this->container->get('sunflower.action');

		echo $action->go();
	}
}